### ISSUE TITLE
State that Cuprite requieres Ruby 2.4

### ISSUE THREAD

**Issue by vizcay** [machinio/cuprite#30]
It will be useful if is stated on the gemspec or README file this requirement or relaxed. Tried to test it with a big Rails app we are on Ruby 2.3.3 and failed because `undefined method "match?" for #<String:0x007fed7b8e30f8>` (https://stackoverflow.com/questions/41792348/nomethoderror-undefined-method-match-for-rubystring):

```
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:144:in `parse_ws_url'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:93:in `start'              
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:31:in `tap'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:31:in `start'              
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:235:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:49:in `initialize'                 
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:22:in `new'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:22:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/driver.rb:26:in `browser'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/driver.rb:135:in `reset!'
```

I will suggest, if you want a bigger pool of colaborators, relax a little this constraint. The reality of a lot of big Rails apps on production is that we lag behind a little on versions.

**Comment by route** [comment]
@vizcay You can try using it from github until we release new version. It's now gone and should be working with ruby 2.3

**Comment by vizcay** [comment]
I'm on  revision 85177260d0c03258d0d109648a72b6aa8f93fe24 and is still failing:

```
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:144:in `parse_ws_url'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:93:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:31:in `tap'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser/process.rb:31:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:235:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:49:in `initialize'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:22:in `new'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/browser.rb:22:in `start'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/driver.rb:26:in `browser'
# /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-85177260d0c0/lib/capybara/cuprite/driver.rb:135:in `reset!'
```

**Comment by route** [comment]
@vizcay sorry you are right, I'll fix it now

**Comment by route** [comment]
@vizcay tests are passing for ruby 2.3, just pushed changes

**Comment by vizcay** [comment]
@route great, now it's working 👍 I will benchmark the results.. as far as I can tell, is faster than chromedriver but slower than phantomjs.
